FORMAT: 1A
HOST: http://www.lan.com

# Latam API Checkin
API Rest para la aplicación checkin de LAN.com


## Reservation Information [/ws/api/checkin/1.0/rest/reservation/information]
### Get reservation information [GET]

+ Request (application/json)
       
        {
            "portal": "empresas",
            "application": "checkin",
            "country": "BR",
            "language": "PT",
            "check_input": "6VKQD5",
            "lastName": "SIMPSON"
        }

        
+ Response 200 (application/json)

    + Header

            flowId:a4f390e1-af0d-4bcd-8682-fd932d2d8ad
            trackId:4264964            
    
    + Body

            {
                "status": {
                    "code": 200
                },
                "data": {
                    "bookings" :[ 
                        {
                            "id" :1,                            
                            "recordLocator": "asdfds",
                            "segments" :[
                                {                                 
                                    "id" : 1,
                                    "flights":[
                                        {
                                            "id" : 1,        
                                            "flightNumber": 23323,
                                            "operatingAirlineCode":"JJ",
                                            "marketinfAirlineCode":"LA",
                                            "departureData" : {
                                                "departureCity": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "departureAirport": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "estimatedDepartureDateTime" : "2014-05-07T16:07"
                                            },
                                            "arrivalData" : {
                                                    "arrivalCity": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                    
                                                 "arrivalAirport": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                "estimatedArrivalDateTime" : "2014-05-07T17:38"
                                            },
                                            "connectionWith": 2,
                                            "status" : "OPEN",
                                            "isLeg": false,
                                            "messages" :[
                                                {
                                                    "text":"Este vuelo esta abierto para checkin"
                                                }
                                            ],
                                            "passengers" : [ 
                                                {
                                                    "id" : 1,
                                                    "ticketNumber":"04534245452342" ,
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : true   
                                                    }
                                                },
                                                {    
                                                    "id" : 2,
                                                    "ticketNumber" : "04534245452343",
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : true     
                                                    }
                                                },
                                                {
                                                    "id" :3,
                                                    "ticketNumber":"04534245452344",
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : true    
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "id" : 2,
                                            "flightNumber": 23324,
                                            "operatingAirlineCode":"JJ",
                                            "marketinfAirlineCode":"LA",
                                            "departureData" : {
                                                "departureCity": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "departureAirport": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "estimatedDepartureDateTime" : "2014-05-07T16:07"
                                            },
                                            "arrivalData" : {
                                                    "arrivalCity": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                    
                                                 "arrivalAirport": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                "estimatedArrivalDateTime" : "2014-05-07T17:38"
                                            },
                                            "connectionWith": 4,
                                            "status": "CLOSED",
                                            "isLeg": false,
                                            "messages" :[
                                                {
                                                    "text":"Vuelo cerrado para checkin por que aun no se abre"
                                                },
                                                {
                                                    "text":"Por favor dirigirse al counter"
                                                }
                                            ],
                                            "passengers" : [
                                                {
                                                    "id" : 1,
                                                    "ticketNumber" : "04534245452342",
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                },
                                                {
                                                    "id" : 2,   
                                                    "ticketNumber":"04534245452343",
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                },
                                                {
                                                    "id" : 3,
                                                    "ticketNumber": "04534245452344",
                                                    "status" : "DISABLE",
                                                    "messages" : [
                                                        {
                                                            "text" : "Pasajero no habilitado para checkin por que es un terrorista"
                                                        }
                                                    ],
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            "id" : 4,
                                            "flightNumber": 23325,
                                            "operatingAirlineCode":"JJ",
                                            "marketinfAirlineCode":"LA",
                                            "departureData" : {
                                                "departureCity": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "departureAirport": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "estimatedDepartureDateTime" : "2014-05-07T16:07"
                                            },
                                            "arrivalData" : {
                                                    "arrivalCity": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                    
                                                 "arrivalAirport": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                "estimatedArrivalDateTime" : "2014-05-07T17:38"
                                            },
                                            "isLeg": true,
                                            "connectionWith": null,
                                            "status": "CLOSED",
                                            "messages" :[
                                                {
                                                    "text":"Vuelo cerrado para checkin por que aun no se abre"
                                                },
                                                {
                                                    "text":"Por favor dirigirse al counter"
                                                }
                                            ],
                                            "passengers" : [ 
                                                {
                                                    "id":1,
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                },
                                                {
                                                    "id" :"2",
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                },
                                                {
                                                    "id" :"3",
                                                    "status" : "DISABLE",
                                                    "messages" : [
                                                        {
                                                            "text" : "Pasajero no habilitado para checkin por que es un terrorista"
                                                        }
                                                    ],
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                }
                                            ]                                    
                                        }
                                    ],
                                    "status":"NO_CHEQUEABLE",
                                    "messages" :[
                                        {
                                            "text":"Segmento no chequeble"
                                        }
                                    ]    
                                },
                                {
                                    "id": 2,
                                    "flights": [
                                        {
                                            "id" : 5,        
                                            "flightNumber": 23323,
                                            "operatingAirlineCode":"JJ",
                                            "marketinfAirlineCode":"LA",
                                            "departureData" : {
                                                "departureCity": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "departureAirport": {
                                                    "code" : "IGU",
                                                    "name" : "Foz de Iguazu"
                                                },
                                                "estimatedDepartureDateTime" : "2014-05-07T16:07"
                                            },
                                            "arrivalData" : {
                                                    "arrivalCity": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                    
                                                 "arrivalAirport": {
                                                    "code" : "SCL",
                                                    "name" : "Santiado de Chile"
                                                },
                                                "estimatedArrivalDateTime" : "2014-05-07T17:38"
                                            },
                                            "status" : "OPEN",
                                            "messages" :[
                                                {
                                                    "text":"Vuelo abierto para checkin"
                                                }
                                            ],
                                            "isLeg": true,
                                            "connectionWith": null,
                                            "passengers" : [
                                                {
                                                    "id" : 2,
                                                    "status" : "ENABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false     
                                                    }
                                                },
                                                {
                                                    "id":"3",
                                                    "status" : "DISABLE",
                                                    "documents" : {
                                                        "boardingpasspdf" : "ENABLE",
                                                        "emailboardingpass" : "ENABLE",
                                                        "mobileboardingpass" : "DISABLE",
                                                        "precheckvoucher" : false    
                                                    },
                                                    "messages" : [
                                                        {
                                                            "text" : "Pasajero no habilitado para checkin por que es un terrorista"
                                                        }
                                                    ]
                                                }
                                            ]    
                                        }           
                                    ],
                                    "status" : "CHEQUEABLE",
                                    "messages" :[
                                        {
                                            "text":"Segmento chequeble "
                                        }
                                    ]            
                                }
                            ],
                            "passengers" : [ 
                                {
                                    "id" : 1,
                                    "ticketNumber": "04534245452342",
                                    "name" : "TUTO",
                                    "lastName" : "PEREZ",
                                    "gender" : "MALE",
                                    "frequentFlyerProgram" : "JJ",
                                    "frequentFlyerNumber" : 23453254,
                                    "type" : "ADT"
                                },
                                {
                                    "id" : 2,
                                    "ticketNumber": "04534245452343",
                                    "name" : "TUTIN",
                                    "lastName" : "PEREZ",
                                    "gender" : "MALE",
                                    "frequentFlyerProgram" : "JJ",
                                    "frequentFlyerNumber" : 23453254,
                                    "type" : "CHD"
                                },
                                {
                                    "id" : 3,
                                    "ticketNumber": "04534245452344",
                                    "name" : "TUTITO",
                                    "lastName" : "PEREZ",
                                    "gender" : "MALE",
                                    "frequentFlyerProgram" : "JJ",
                                    "frequentFlyerNumber" : 23453254,
                                    "type" : "INF"
                                }
                            ]
                        }
                    ]    
                }
            }






+ Response 501 (application/json)

        { "title": "No paso la validacion del apellido o record locator, intente de nuevo" } 

+ Response 502 (application/json)

        { "title": "Error llamando al servicio, trate en un rato" }         

+ Response 503 (application/json)

        { "title": "No disponible el checkin" }

+ Response 510 (application/json)

        { "title": "Reserva inhibida para checkin" }

+ Response 521 (application/json)

        { "title": "Redirigiendo a sitio tam", "url" : "tam.com.br/supercheckindetam" }

