FORMAT: 1A
HOST: http://www.lan.com

# Latam API Checkin
API Rest para la aplicación checkin de LAN.com


## Reservation Information [/reservation/information]
### Get reservation information [GET]

+ Request (application/json)
       
        {
            lastName: "string",
            application: "string",
            checkInput: "string",
            portal: "string",
            language: "string",
            serviceName: "string,
            country: "prueba2"
        }
        
+ Response 200 (application/json)

    + Header

            flowId:a4f390e1-af0d-4bcd-8682-fd932d2d8ad
            trackId:4264964            
    
    + Body

            {
                "status": {
                    "message": "string",
                    "code": "prueba2"
                },
                "data": {
                    "recordLocator": "string" 

                }             
            }
       
       
+ Response 501 (application/json)

        { "id": 3, "title": "Buy cheese and bread for breakfast." }       
       


